"""fix_drug_reference_pk

Revision ID: 3177ba9a47cd
Revises: 6d13dec19de0
Create Date: 2026-09-19 22:45:37.177312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3177ba9a47cd'
down_revision: Union[str, Sequence[str], None] = '6d13dec19de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_reference', sa.Column('id', sa.String(length=36), nullable=False))
    op.create_unique_constraint('uq_drug_rxcui_brand', 'drug_reference', ['rxcui', 'brand'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_drug_rxcui_brand', 'drug_reference', type_='unique')
    op.drop_column('drug_reference', 'id')
    # ### end Alembic commands ###
